author: Abel Borges
title: Data interlude
email: brgs.abel@gmail.com
description: Personal collection of thoughts on data analysis
baseurl: "" # the subpath of your site, e.g. /blog
url: "abelborges.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: abelborges

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:title/
